<?php


use App\Src\Mailer;

if (isset($_POST["name"], $_POST["email"], $_POST["subject"], $_POST["body"])) {
    Mailer::sendMail($_POST["subject"],$_POST["name"], $_POST["email"], $_POST["body"]);
}

?>

<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
        }
        .contact {
            width: 100%;
            height: 100vh;
            display: grid;
            place-content: center;
        }

        .contact__title {
            margin-bottom: 20px;
            text-align: center;
        }

        .contact__form {
            display: flex;
            justify-content: space-around;
            flex-direction: column;
        }

        .contact__form > * {
            margin-bottom: 20px;
        }

        .contact__form:last-child {
            margin-bottom: 0;
        }

        .contact__form input, .contact__form textarea {
            padding: 10px;
            height: 40px;
            border-radius: 5px;
            border: 1px solid rebeccapurple;
            resize: vertical;

        }

        .contact__form button {
            height: 40px;
            background: rebeccapurple;
            color: whitesmoke;
            border-radius: 5px;
            border: none;
            cursor: pointer;
        }
    </style>
</head>
<body>

<section class="contact">
    <h1 class="contact__title">Contact</h1>
    <form class="contact__form" method="post" >
        <label for="name">Name</label>
        <input type="text" name="name" id="name" autocomplete="off" required>
        <label for="email">Email</label>
        <input type="email" name="email" id="email"  autocomplete="off" required>
        <label for="subject">Subject</label>
        <input type="text" name="subject" id="subject"  autocomplete="off" required>
        <label for="body">Message</label>
        <textarea name="body" id="body" cols="30" rows="10"  autocomplete="off" required></textarea>
        <button type="submit">Send</button>
    </form>
</section>

</body>
</html>