<?php


use App\Src\Mailer;

if (isset($_POST["name"], $_POST["email"], $_POST["subject"], $_POST["body"])) {
    Mailer::sendMail($_POST["subject"],$_POST["name"], $_POST["email"], $_POST["body"]);
}

?>

<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no>
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Contact</title>
</head>
<body>

<section>
    <h1>Contact</h1>
    <form action="" method="post">
        <label for="name">Name</label>
        <input type="text" name="name" id="name" required>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required>
        <label for="subject">Subject</label>
        <input type="text" name="subject" id="subject" required>
        <label for="body">Message</label>
        <textarea name="body" id="body" cols="30" rows="10" required></textarea>
        <button type="submit">Send</button>
    </form>
</section>

</body>
</html>